#!/bin/bash
# DHako Database & Render Setup Quick Reference
# Run from project root: bash QUICK_SETUP.sh

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          DHako Deployment Setup - Quick Reference             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 STEP 1: Initialize Database Locally${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this command from your backend directory:"
echo ""
echo -e "${GREEN}  cd backend${NC}"
echo -e "${GREEN}  node init-db.js${NC}"
echo ""
echo "This will:"
echo "  ✓ Connect to Render PostgreSQL"
echo "  ✓ Create all database tables"
echo "  ✓ Seed initial data"
echo "  ✓ Verify setup success"
echo ""

echo -e "${BLUE}📋 STEP 2: Database Connection Details${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Your Render PostgreSQL:"
echo ""
echo "  Host:     dpg-da7vmi0ae00c73a9i5i0-a.onrender.com"
echo "  Port:     5432"
echo "  Database: dhako"
echo "  User:     dhako_user"
echo "  Password: eH4lDu614dfwTpVVqXp1VvPFUqA3Uzgj"
echo ""
echo "Full URL:"
echo "  postgresql://dhako_user:eH4lDu614dfwTpVVqXp1VvPFUqA3Uzgj@dpg-da7vmi0ae00c73a9i5i0-a.onrender.com:5432/dhako"
echo ""

echo -e "${BLUE}📋 STEP 3: Set Environment Variables on Render${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Backend Service Settings → Environment:"
echo ""
echo "  DATABASE_URL = postgresql://dhako_user:eH4lDu614dfwTpVVqXp1VvPFUqA3Uzgj@dpg-da7vmi0ae00c73a9i5i0-a.onrender.com:5432/dhako"
echo "  NODE_ENV = production"
echo "  JWT_SECRET = (generate strong random key)"
echo "  JWT_EXPIRES_IN = 7d"
echo "  FRONTEND_URL = https://your-frontend-url.onrender.com"
echo ""

echo -e "${BLUE}📋 STEP 4: Set Frontend Environment Variables${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Frontend Service Settings → Environment:"
echo ""
echo "  VITE_API_URL = https://your-backend-url.onrender.com"
echo ""
echo "Find backend URL in: Backend Service → URL at top of page"
echo ""

echo -e "${BLUE}📋 STEP 5: Test the Setup${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test backend health:"
echo -e "${GREEN}  curl https://your-backend-url.onrender.com/health${NC}"
echo ""
echo "Expected response:"
echo -e "${GREEN}  { \"status\": \"ok\", \"timestamp\": \"...\" }${NC}"
echo ""
echo "Test login with:"
echo "  Email:    admin@dhako.com"
echo "  Password: admin123"
echo ""

echo -e "${BLUE}📋 STEP 6: Verify Database Connection${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option A - Check Render Logs:"
echo "  1. Go to Backend Service"
echo "  2. Click 'Logs' tab"
echo "  3. Look for: ✅ Connected to PostgreSQL"
echo ""
echo "Option B - Connect with pgAdmin locally:"
echo "  Host:     dpg-da7vmi0ae00c73a9i5i0-a.onrender.com"
echo "  Port:     5432"
echo "  Database: dhako"
echo "  User:     dhako_user"
echo "  Password: eH4lDu614dfwTpVVqXp1VvPFUqA3Uzgj"
echo ""

echo -e "${YELLOW}⚠️  IMPORTANT SECURITY NOTES:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  • Change JWT_SECRET in production to a strong random value"
echo "  • Never commit .env files with real credentials"
echo "  • Rotate database password if credentials were exposed"
echo "  • Use HTTPS for all connections (Render provides this)"
echo ""

echo -e "${BLUE}📋 Useful Commands:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Generate strong JWT secret:"
echo -e "${GREEN}  openssl rand -base64 32${NC}"
echo ""
echo "Test Render backend is running:"
echo -e "${GREEN}  curl https://your-backend-url.onrender.com/health${NC}"
echo ""
echo "Watch Render logs in real-time:"
echo "  1. Go to service on Render Dashboard"
echo "  2. Click 'Logs' tab"
echo "  3. Watch for deployment events"
echo ""

echo -e "${GREEN}✅ Setup Complete!${NC}"
echo ""
echo "For detailed troubleshooting, see:"
echo "  - DATABASE_SETUP.md"
echo "  - RENDER_DEPLOYMENT_CHECKLIST.md"
echo ""
